
/****** Object:  Table [dbo].[A_BARCODE]    Script Date: 12/31/2015 01:14:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[A_BARCODE](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[BARCODE] [varchar](50) NULL,
	[STATUS] [int] NULL,
 CONSTRAINT [PK_A_BARCODE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[A_BARCODE] ADD  CONSTRAINT [DF_A_BARCODE_STATUS]  DEFAULT ((0)) FOR [STATUS]
GO

